version: "3.8"

services:
    cinema.pgsql:
        image: postgres:12.4-alpine
        container_name: cinema.pgsql
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PASSWORD=123qwe
            - POSTGRES_DB=cinemadb
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/db:/var/lib/postgresql/data/pgdata